### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by brandoncroberts** [chantastic/ama#10]
What are your thoughts on Typescript and do you think it will “take over the JS world”.
Like said here https://hub.packtpub.com/4-predictions-by-richard-feldman-on-the-future-of-the-web-typescript-webassembly-and-more/ ?

**Comment by brandoncroberts** [comment]
Yes I'm aware it's TypeScript . Misspelled the title

**Comment by chantastic** [comment]
Hey @8brandon thanks fro the question!

"Take over the JS world" feels intentionally vague 😅

TypeScript is on fire and will continue to accelerate in popularity and practice.
I use TypeScript and love it but I still identify as a JavaScript developer.

Speaking in specific terms, I agree that TS could quickly come to represent the majority of source (precompiled) JavaScript.
But there's no way it could every overtake JavaScript as we know it today — a language that can effectively be run on any modern device.

I wouldn't be surprised if — in the long term — JavaScript adopted some form of incremental type annotations.
I'd love to see that.
